option('x11', type: 'feature', value: 'auto', description: 'Enable X11 support')
option('wayland', type: 'feature', value: 'auto', description: 'Enable Wayland support')
option('xrandr', type: 'feature', value: 'auto', description: 'Enable XRandR support')
option('eds', type: 'feature', value: 'auto', description: 'Enable Evolution Data Server calendar integration')
option('introspection', type: 'boolean', value: true, description: 'Build GObject Introspection data')
option('gtk-doc', type: 'boolean', value: false, description: 'Build developer documentation')
